name: 'Vanessa & Ralph'
favicon: null
layout_spectrum: 0.2548
typography_spectrum: 0.21002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f6558'
    - '#473d32'
    - '#c9c3b5'
    - '#eee8da'
    - '#241005'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
